# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longUrl', models.CharField(max_length=1000)),
                ('shortUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
